version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

volumes:
  db_data:
