version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D1sc0rd!
      MYSQL_DATABASE: bot_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: D1sc0rd!
      DB_NAME: bot_db
    depends_on:
      - db

volumes:
  db_data:
